default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  database: <%= ENV["DATABASE_NAME"] %>
  port: 3306
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOSTNAME"]%>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"]%>

staging:
  <<: *default

production:
  <<: *default
